# IMPORT ENV
spring.config.import=optional:file:.env[.properties]
spring.application.name=app_comiqueria

# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=${DB_PLATFORM}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=true


# ===============================
# CORS
# ===============================
cors.allowed-origin=${CORS_ALLOWED_ORIGIN}


# ===============================
# JWT
# ===============================
application.security.jwt.secret-key=${JWT_SECRET_KEY}
#application.security.jwt.secret-key=usqcDy0Z73XHe35oMJbnJfS1I4jvDXEsYtk5vDLBRVo=
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000


# ===============================
# LOGS
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.boot.context.config=TRACE


# ===============================
# DEVTOOLS
# ===============================
spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=static/**,public/**


# ===============================
# SPRING MAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=${GMAIL_PORT}
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false


# ===============================
# FRONTEND
# ===============================
app.frontend.reset-password-url=${FRONT_RESET_PASSWORD_URL}

server.port=8080
